name: Run Complete Quest

on:
  workflow_dispatch:      # cho phép bấm chạy thủ công trong tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "npm"

      - name: Overwrite .env with real token
        run: echo "TOKEN=${{ secrets.TOKEN }}" > .env
        
      - name: Install dependencies
        run: npm install

      - name: Run Quest
        timeout-minutes: 30
        run: npm run go
